package gui.controller;

import gui.GUIFile;
import gui.model.ImportWizardModel;
import gui.view.ImportWizardDialog;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.opendatafoundation.data.spss.SPSSFile;
import org.opendatafoundation.data.spss.SPSSFileException;

/**
 * This class is responsible for reacting to events generated by pushing any of the
 * three buttons, 'Next', 'Previous', and 'Cancel.' Based on what button is pressed,
 * the controller will update the model to show a new panel and reset the state of
 * the buttons as necessary.
 */
public class ImportWizardController implements ActionListener {
    
    private ImportWizardDialog hostPanel;
    private GUIFile guiFile;
    
    /**
     * This constructor accepts a reference to the Wizard component that created it,
     * which it uses to update the button components and access the WizardModel.
     * @param w A callback to the Wizard component that created this controller.
     */    
    public ImportWizardController(ImportWizardDialog w, GUIFile guiFile) {
        hostPanel = w;
        this.guiFile = guiFile;
    }

    /**
     * Calling method for the action listener interface. This class listens for actions
     * performed by the buttons in the Wizard class, and calls methods below to determine
     * the correct course of action.
     * @param evt The ActionEvent that occurred.
     */    
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        
        if (evt.getActionCommand().equals(ImportWizardDialog.CANCEL_BUTTON_ACTION_COMMAND))
            cancelButtonPressed();
        else if (evt.getActionCommand().equals(ImportWizardDialog.BACK_BUTTON_ACTION_COMMAND))
            backButtonPressed();
        else if (evt.getActionCommand().equals(ImportWizardDialog.NEXT_BUTTON_ACTION_COMMAND))
            nextButtonPressed();
        else if (evt.getActionCommand().equals(ImportWizardDialog.OPEN_SPSS_FILE_ACTION_COMMAND))
            nextButtonPressed();
        else if (evt.getActionCommand().equals(ImportWizardDialog.CHARSET_COMBO_BOX_ACTION))
            nextButtonPressed();
        else if (evt.getActionCommand().equals(ImportWizardDialog.IMPORT_SPSS_FILE_ACTION))
            nextButtonPressed();
        
    }
    
    public void openSpssFileAction() {
		JFileChooser fc = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"SPSS Files", "sav");
		fc.setFileFilter(filter);

		int returnVal = fc.showOpenDialog(this.hostPanel);

		if (returnVal == JFileChooser.APPROVE_OPTION) {

			File file = fc.getSelectedFile();
			System.out.println("Opening file: " + file.getName() + ".");

			// import SPSS file.
			try {
				SPSSFile spssFile = new SPSSFile(file, "r");
				spssFile.logFlag = false;
				spssFile.loadMetadata();
				spssFile.close();
				
				guiFile.setSpssFile(file);
				String text = "File selected: " + guiFile.getSpssFile().getName();
				hostPanel.setSpssFileInfoText(text);
				
			} catch (FileNotFoundException e1) {
				System.out.println("SPSS file open failed.");
				JOptionPane.showMessageDialog(this.hostPanel,
						"You must select a valid SPSS file.",
						"Daxplore file warning", JOptionPane.ERROR_MESSAGE);
				e1.printStackTrace();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (SPSSFileException e1) {
				System.out.println("Not a valid SPSS file.");
				JOptionPane.showMessageDialog(this.hostPanel,
						"You must select a valid SPSS file.",
						"Daxplore file warning", JOptionPane.ERROR_MESSAGE);
				e1.printStackTrace();
			}
		}
	}
    
       
    private void cancelButtonPressed() {
        
        hostPanel.close(ImportWizardDialog.CANCEL_RETURN_CODE);
    }

    private void nextButtonPressed() {
 
        ImportWizardModel model = hostPanel.getModel();
        ImportWizardDescriptor descriptor = model.getCurrentPanelDescriptor();
        
        //  If it is a finishable panel, close down the dialog. Otherwise,
        //  get the ID that the current panel identifies as the next panel,
        //  and display it.
        
        Object nextPanelDescriptor = descriptor.getNextPanelDescriptor();
        
        if (nextPanelDescriptor instanceof ImportWizardDescriptor.FinishIdentifier) {
            hostPanel.close(Wizard.FINISH_RETURN_CODE);
        } else {        
            hostPanel.setCurrentPanel(nextPanelDescriptor);
        }
        
    }

    private void backButtonPressed() {
 
        ImportWizardModel model = hostPanel.getModel();
        ImportWizardDescriptor descriptor = model.getCurrentPanelDescriptor();
 
        //  Get the descriptor that the current panel identifies as the previous
        //  panel, and display it.
        
        Object backPanelDescriptor = descriptor.getBackPanelDescriptor();        
        hostPanel.setCurrentPanel(backPanelDescriptor);
        
    }

    void resetButtonsToPanelRules() {
    
        //  Reset the buttons to support the original panel rules,
        //  including whether the next or back buttons are enabled or
        //  disabled, or if the panel is finishable.
        
        WizardModel model = hostPanel.getModel();
        WizardPanelDescriptor descriptor = model.getCurrentPanelDescriptor();
        
        model.setCancelButtonText(ImportWizardDialog.CANCEL_TEXT);
        model.setCancelButtonIcon(ImportWizardDialog.CANCEL_ICON);
        
        //  If the panel in question has another panel behind it, enable
        //  the back button. Otherwise, disable it.
        
        model.setBackButtonText(ImportWizardDialog.BACK_TEXT);
        model.setBackButtonIcon(ImportWizardDialog.BACK_ICON);
        
        if (descriptor.getBackPanelDescriptor() != null)
            model.setBackButtonEnabled(Boolean.TRUE);
        else
            model.setBackButtonEnabled(Boolean.FALSE);

        //  If the panel in question has one or more panels in front of it,
        //  enable the next button. Otherwise, disable it.
 
        if (descriptor.getNextPanelDescriptor() != null)
            model.setNextFinishButtonEnabled(Boolean.TRUE);
        else
            model.setNextFinishButtonEnabled(Boolean.FALSE);
 
        //  If the panel in question is the last panel in the series, change
        //  the Next button to Finish. Otherwise, set the text back to Next.
        
        if (descriptor.getNextPanelDescriptor() instanceof WizardPanelDescriptor.FinishIdentifier) {
            model.setNextFinishButtonText(ImportWizardDialog.FINISH_TEXT);
            model.setNextFinishButtonIcon(ImportWizardDialog.FINISH_ICON);
        } else {
            model.setNextFinishButtonText(ImportWizardDialog.NEXT_TEXT);
            model.setNextFinishButtonIcon(ImportWizardDialog.NEXT_ICON);
        }
        
    }
    
    
}